# Generated by Django 5.2.6 on 2025-09-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habittracker', '0002_habit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='note',
        ),
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
